# Generated by Django 3.2 on 2021-04-10 00:31

from django.db import migrations
import pypro.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pypro.base.models.UserManager()),
            ],
        ),
    ]
